import React, { useState } from 'react';
import {
  AlertTriangle,
  CheckCircle2,
  FileText,
  Trash2,
  Plus,
  MinusCircle,
  Edit3,
  PlusCircle,
  Download,
  Code2,
  GitCompare,
  Layers,
  ShieldCheck,
  Zap,
  HelpCircle
} from 'lucide-react';
import { INITIAL_SCOPE_DELTAS } from '../data/simulationPresets';
import { ScopeDeltaItem } from '../types';

export const ScopeDeltaAnalysis: React.FC = () => {
  const [deltas, setDeltas] = useState<ScopeDeltaItem[]>(INITIAL_SCOPE_DELTAS);
  const [selectedFilter, setSelectedFilter] = useState<'ALL' | 'DROPPED' | 'MODIFIED' | 'ADDED'>('ALL');
  const [activeDiffTab, setActiveDiffTab] = useState<'deprecated' | 'active'>('deprecated');

  const [showAddModal, setShowAddModal] = useState(false);
  const [newItem, setNewItem] = useState<Partial<ScopeDeltaItem>>({
    type: 'DROPPED',
    title: '',
    description: '',
    rationale: '',
    impactScore: 'High',
    architecturalLayer: 'Worker',
    replacesOrDeprecates: '',
  });

  const handleAddDelta = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newItem.title || !newItem.rationale) return;

    const entry: ScopeDeltaItem = {
      id: `sd-${Date.now()}`,
      type: newItem.type as any || 'DROPPED',
      title: newItem.title || '',
      description: newItem.description || '',
      rationale: newItem.rationale || '',
      impactScore: newItem.impactScore as any || 'Medium',
      architecturalLayer: newItem.architecturalLayer as any || 'Worker',
      replacesOrDeprecates: newItem.replacesOrDeprecates,
    };

    setDeltas([entry, ...deltas]);
    setShowAddModal(false);
    setNewItem({
      type: 'DROPPED',
      title: '',
      description: '',
      rationale: '',
      impactScore: 'High',
      architecturalLayer: 'Worker',
      replacesOrDeprecates: '',
    });
  };

  const handleDeleteDelta = (id: string) => {
    setDeltas(deltas.filter((d) => d.id !== id));
  };

  const filteredDeltas = deltas.filter(
    (d) => selectedFilter === 'ALL' || d.type === selectedFilter
  );

  const droppedCount = deltas.filter((d) => d.type === 'DROPPED').length;
  const modifiedCount = deltas.filter((d) => d.type === 'MODIFIED').length;
  const addedCount = deltas.filter((d) => d.type === 'ADDED').length;

  const downloadScopeDeltaMarkdown = () => {
    const md = `# Assignment 2: Scope Delta Analysis & Architectural Trade-off Record
**Project**: Northstar Retail Co. Live Inventory Sync Service
**Sprint Event**: The Meridian Pivot (Day 4 Polling Decommissioning)

## Executive Summary
Following the client's non-negotiable directive on Day 4, the engineering team dismantled the periodic 5-minute warehouse polling infrastructure and replaced it with a zero-staleness HMAC-SHA256 Webhook Push architecture.

## 1. Scope Delta Breakdown

### A. Dropped Features & Code (${droppedCount})
${deltas
  .filter((d) => d.type === 'DROPPED')
  .map(
    (d) => `#### [DROPPED] ${d.title}
- **Layer**: ${d.architecturalLayer} | **Impact**: ${d.impactScore}
- **Description**: ${d.description}
- **Rationale**: ${d.rationale}
- **Decommissioned Path**: \`${d.replacesOrDeprecates || 'N/A'}\`
`
  )
  .join('\n')}

### B. Modified Architectural Components (${modifiedCount})
${deltas
  .filter((d) => d.type === 'MODIFIED')
  .map(
    (d) => `#### [MODIFIED] ${d.title}
- **Layer**: ${d.architecturalLayer} | **Impact**: ${d.impactScore}
- **Description**: ${d.description}
- **Rationale**: ${d.rationale}
`
  )
  .join('\n')}

### C. Newly Added Ingress & Protection Services (${addedCount})
${deltas
  .filter((d) => d.type === 'ADDED')
  .map(
    (d) => `#### [ADDED] ${d.title}
- **Layer**: ${d.architecturalLayer} | **Impact**: ${d.impactScore}
- **Description**: ${d.description}
- **Rationale**: ${d.rationale}
`
  )
  .join('\n')}

## 2. Non-Negotiable Rule Compliance Verification
- [x] **Rule 1**: Unfamiliar tool was genuinely new to the team.
- [x] **Rule 2**: Autonomous troubleshooting evidenced via Day 1-2 Blocker Journal.
- [x] **Rule 3**: Day 4 pivot accepted without deadline extension or scope rollback.
- [x] **Rule 4**: Obsolete polling code explicitly removed/deprecated, not running in parallel.
- [x] **Rule 5**: Adaptability Index maintained as confidential aggregated telemetry.

---
*Generated by Meridian Pivot Simulation Engine (Power Learn Project)*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'assignment-2-scope-delta-analysis.md';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-sm">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-amber-500/20 text-amber-400 border border-amber-500/30">
                Assignment 2 Deliverable (Day 5)
              </span>
              <h2 className="text-base font-bold text-slate-100">
                Scope Delta Analysis & Architectural Deprecation Diff
              </h2>
            </div>
            <p className="text-xs text-slate-400 max-w-3xl">
              Documents exactly what the Day 4 pivot cost: what was dropped, modified, and added. Proves adherence to <strong>Non-Negotiable Rule #4</strong> (obsolete polling code must be visibly removed/deprecated, not run in parallel).
            </p>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={downloadScopeDeltaMarkdown}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Scope Delta (.md)</span>
            </button>
            <button
              onClick={() => setShowAddModal(true)}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold bg-rose-600 hover:bg-rose-500 text-white shadow transition cursor-pointer"
            >
              <Plus className="w-4 h-4" />
              <span>Add Delta Item</span>
            </button>
          </div>
        </div>

        {/* Delta Counts Summary */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4 pt-4 border-t border-slate-800/80 text-xs">
          <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800">
            <span className="text-slate-400 block text-[11px]">Dropped Code / Items</span>
            <span className="text-sm font-bold text-rose-400 flex items-center gap-1 mt-0.5">
              <MinusCircle className="w-4 h-4" /> {droppedCount} Components
            </span>
          </div>
          <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800">
            <span className="text-slate-400 block text-[11px]">Modified Pipelines</span>
            <span className="text-sm font-bold text-amber-400 flex items-center gap-1 mt-0.5">
              <Edit3 className="w-4 h-4" /> {modifiedCount} Pipelines
            </span>
          </div>
          <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800">
            <span className="text-slate-400 block text-[11px]">Added Ingress Services</span>
            <span className="text-sm font-bold text-emerald-400 flex items-center gap-1 mt-0.5">
              <PlusCircle className="w-4 h-4" /> {addedCount} Push Services
            </span>
          </div>
          <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800">
            <span className="text-slate-400 block text-[11px]">Rule #4 Compliance</span>
            <span className="text-sm font-bold text-emerald-400 flex items-center gap-1 mt-0.5">
              <ShieldCheck className="w-4 h-4" /> Polling Decommissioned
            </span>
          </div>
        </div>
      </div>

      {/* Code Refactoring & Deprecation Diff Inspector */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <GitCompare className="w-4 h-4 text-rose-400" />
            <h3 className="font-bold text-sm text-slate-100">
              Architectural Code Diff: Legacy Polling vs. Webhook Push
            </h3>
          </div>

          <div className="flex items-center gap-2 bg-slate-950 p-1 rounded-xl border border-slate-800">
            <button
              onClick={() => setActiveDiffTab('deprecated')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition ${
                activeDiffTab === 'deprecated'
                  ? 'bg-rose-950 text-rose-300 border border-rose-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              src/workers/WarehousePoller.ts (DEPRECATED)
            </button>
            <button
              onClick={() => setActiveDiffTab('active')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition ${
                activeDiffTab === 'active'
                  ? 'bg-emerald-950 text-emerald-300 border border-emerald-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              src/controllers/PushWebhookController.ts (ACTIVE)
            </button>
          </div>
        </div>

        {activeDiffTab === 'deprecated' ? (
          <div className="space-y-2">
            <div className="flex items-center justify-between text-xs px-2 text-rose-400 font-mono">
              <span className="flex items-center gap-1.5">
                <MinusCircle className="w-3.5 h-3.5" />
                STATUS: @deprecated - Removed from active runtime orchestrator
              </span>
              <span className="text-slate-500">Day 3 Codebase (Scrapped)</span>
            </div>
            <pre className="bg-slate-950 p-4 rounded-xl border border-rose-500/30 text-[11px] font-mono text-slate-400 overflow-x-auto leading-relaxed line-through decoration-rose-500/60">
{`/**
 * @deprecated DEPRECATED AS OF DAY 4 PIVOT (NORTHSTAR SPRINT 2)
 * Polling API is being decommissioned in 48 hours.
 * Replaced by PushWebhookController with HMAC-SHA256 verification.
 */
export class LegacyWarehousePoller {
  private intervalId: NodeJS.Timeout | null = null;
  private readonly POLL_INTERVAL_MS = 300_000; // 5 minutes

  public start() {
    console.warn('[DEPRECATED] Periodic polling causes 300s staleness and warehouse server CPU overload.');
    // DISABLED: this.intervalId = setInterval(() => this.pollWarehouseStock(), this.POLL_INTERVAL_MS);
  }

  public stop() {
    if (this.intervalId) clearInterval(this.intervalId);
  }
}`}
            </pre>
          </div>
        ) : (
          <div className="space-y-2">
            <div className="flex items-center justify-between text-xs px-2 text-emerald-400 font-mono">
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="w-3.5 h-3.5" />
                STATUS: ACTIVE - Handling live warehouse push notifications
              </span>
              <span className="text-slate-500">Day 4–5 Production Endpoint</span>
            </div>
            <pre className="bg-slate-950 p-4 rounded-xl border border-emerald-500/30 text-[11px] font-mono text-slate-200 overflow-x-auto leading-relaxed">
{`// src/controllers/PushWebhookController.ts
import { Request, Response } from 'express';
import { verifyWebhookSignature } from '../security/hmacVerifier';
import { stockCache } from '../cache/redisStockCache';

export async function handleWarehouseStockPush(req: Request, res: Response) {
  const signature = req.header('X-Northstar-Signature');
  const rawBody = req.body; // Captured via express.raw()

  // 1. Verify Cryptographic HMAC & 300s Anti-Replay Drift
  const auth = verifyWebhookSignature(rawBody, signature, process.env.WEBHOOK_SECRET!);
  if (!auth.isValid) {
    return res.status(401).json({ error: 'Unauthorized Webhook Signature', reason: auth.reason });
  }

  // 2. Parse Validated Event
  const { sku, warehouseStock, timestamp } = JSON.parse(rawBody);

  // 3. Atomically Update Cache Store (<5ms)
  await stockCache.setStock(sku, warehouseStock);

  // 4. Return Fast Acknowledgment
  return res.status(200).json({ acknowledged: true, sku, syncedAt: Date.now() });
}`}
            </pre>
          </div>
        )}
      </div>

      {/* Scope Delta Filter & List */}
      <div className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">
            Scope Delta Breakdown Items ({filteredDeltas.length})
          </h3>

          <div className="flex items-center gap-1.5 bg-slate-900 p-1 rounded-xl border border-slate-800 text-xs">
            {(['ALL', 'DROPPED', 'MODIFIED', 'ADDED'] as const).map((filter) => (
              <button
                key={filter}
                onClick={() => setSelectedFilter(filter)}
                className={`px-2.5 py-1 rounded-lg font-medium transition ${
                  selectedFilter === filter
                    ? 'bg-slate-800 text-rose-400 border border-slate-700 font-bold'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {filter}
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredDeltas.map((delta) => {
            const isDropped = delta.type === 'DROPPED';
            const isAdded = delta.type === 'ADDED';

            return (
              <div
                key={delta.id}
                className="bg-slate-900 border border-slate-800 rounded-xl p-4 text-xs space-y-3 shadow-sm hover:border-slate-700 transition flex flex-col justify-between"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] font-black tracking-wide ${
                        isDropped
                          ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                          : isAdded
                          ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                          : 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                      }`}
                    >
                      {delta.type}
                    </span>

                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-mono text-slate-400 bg-slate-950 px-1.5 py-0.5 rounded border border-slate-800">
                        {delta.architecturalLayer}
                      </span>
                      <button
                        onClick={() => handleDeleteDelta(delta.id)}
                        className="text-slate-500 hover:text-rose-400 transition"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>

                  <h4 className="font-bold text-sm text-slate-100">{delta.title}</h4>
                  <p className="text-slate-300 leading-relaxed">{delta.description}</p>
                </div>

                <div className="pt-2 border-t border-slate-800 space-y-1.5 text-[11px]">
                  <div>
                    <span className="font-bold text-slate-400">Architectural Rationale: </span>
                    <span className="text-slate-300">{delta.rationale}</span>
                  </div>

                  {delta.replacesOrDeprecates && (
                    <div className="text-rose-400/90 font-mono text-[10px]">
                      Decommissioned: {delta.replacesOrDeprecates}
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Add Delta Modal */}
      {showAddModal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl max-w-lg w-full p-6 space-y-4 shadow-2xl text-xs">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="text-sm font-bold text-slate-100 flex items-center gap-2">
                <FileText className="w-4 h-4 text-rose-400" />
                <span>Add Scope Delta Item</span>
              </h3>
              <button
                onClick={() => setShowAddModal(false)}
                className="text-slate-400 hover:text-slate-200"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleAddDelta} className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-slate-400 block mb-1 font-medium">Delta Type:</label>
                  <select
                    value={newItem.type}
                    onChange={(e) => setNewItem({ ...newItem, type: e.target.value as any })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-rose-500"
                  >
                    <option value="DROPPED">DROPPED (Decommissioned)</option>
                    <option value="MODIFIED">MODIFIED (Refactored)</option>
                    <option value="ADDED">ADDED (New Ingress/Security)</option>
                  </select>
                </div>

                <div>
                  <label className="text-slate-400 block mb-1 font-medium">Layer:</label>
                  <select
                    value={newItem.architecturalLayer}
                    onChange={(e) => setNewItem({ ...newItem, architecturalLayer: e.target.value as any })}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-rose-500"
                  >
                    <option value="Ingress">Ingress / API Gateway</option>
                    <option value="Storage/Cache">Storage / Redis Cache</option>
                    <option value="Worker">Worker / Queue Processor</option>
                    <option value="Client API">Client Support API</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="text-slate-400 block mb-1 font-medium">Feature / Component Title:</label>
                <input
                  required
                  type="text"
                  value={newItem.title}
                  onChange={(e) => setNewItem({ ...newItem, title: e.target.value })}
                  placeholder="e.g. In-memory Polling Batch Diff Buffer"
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-rose-500"
                />
              </div>

              <div>
                <label className="text-slate-400 block mb-1 font-medium">What Changed (Description):</label>
                <textarea
                  required
                  rows={2}
                  value={newItem.description}
                  onChange={(e) => setNewItem({ ...newItem, description: e.target.value })}
                  placeholder="Describe the architectural change and why it was modified..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-rose-500"
                />
              </div>

              <div>
                <label className="text-slate-400 block mb-1 font-medium">Trade-off Rationale:</label>
                <textarea
                  required
                  rows={2}
                  value={newItem.rationale}
                  onChange={(e) => setNewItem({ ...newItem, rationale: e.target.value })}
                  placeholder="Explain why this decision was made under the 48h deadline..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-rose-500"
                />
              </div>

              <div>
                <label className="text-slate-400 block mb-1 font-medium">Deprecated File / Module (Optional):</label>
                <input
                  type="text"
                  value={newItem.replacesOrDeprecates}
                  onChange={(e) => setNewItem({ ...newItem, replacesOrDeprecates: e.target.value })}
                  placeholder="e.g. src/services/WarehousePoller.ts"
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 focus:outline-none focus:border-rose-500"
                />
              </div>

              <div className="flex justify-end gap-2 pt-3 border-t border-slate-800">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 font-medium"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-lg bg-rose-600 hover:bg-rose-500 text-white font-bold"
                >
                  Add to Delta
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
